#pragma once

#include <M5GFX.h>

// AI: below section was generated by an AI

// CoreS3 display hardware boundary.
//
// This class contains only CoreS3 board-dependent Display / Touch /
// brightness / battery access. UI/WLED behavior remains in CoreS3_Display.cpp.
struct M5StackBatteryStatus {
  bool available = false;
  bool present = false;
  bool charging = false;
  uint8_t level = 0;
};

class M5StackDisplayHardwareBackend {
  private:

  M5GFX& display;

  public:

  explicit M5StackDisplayHardwareBackend( M5GFX& displayRef );

  bool initializeDisplay(
    int16_t& screenWidth,
    int16_t& screenHeight,
    bool& touchReady
  );

  bool readTouch( int16_t& touchX, int16_t& touchY );
  void writeBrightness( uint8_t value );

  // Read battery state through the CoreS3 hardware backend.
  // The UI consumes only this generic status object; PMIC/register details
  // stay outside CoreS3_Display.cpp.
  bool readBatteryStatus( M5StackBatteryStatus& status );
};

// AI: end
