[platformio]
default_envs = esp32dev_usermod_AnimatedStaircase_VL53L0X

# Animated Staircase VL53L0X sensors
[env:esp32dev_usermod_AnimatedStaircase_VL53L0X]
extends = env:esp32dev
custom_usermods =
  AnimatedStaircase_VL53L0X
lib_deps = 
  ${env:esp32dev.lib_deps}
  pololu/VL53L0X @ ^1.3.0
build_flags =
  ${env:esp32dev.build_flags}
  -D USERMOD_ANIMATED_STAIRCASE_VL53L0X