/*
 * msgeq7 — Software MSGEQ7 audio-reactive usermod for WLED
 *
 * Produces the same um_data_t 8-slot structure as the audioreactive usermod,
 * making it a drop-in replacement. Uses either:
 *   (A) Software backend: I2S/ADC microphone + 7 biquad bandpass filters at the
 *       classic MSGEQ7 center frequencies (63, 160, 400, 1k, 2.5k, 6.25k, 16k Hz).
 *   (B) Hardware backend: physical MSGEQ7 chip read via strobe/reset/OUT pins.
 *
 * Both backends produce 7 band amplitudes which are then interpolated to fill
 * the 16-channel fftResult[] array expected by WLED effects.
 *
 * Registers as USERMOD_ID_AUDIOREACTIVE (32) so all existing audio-reactive
 * effects work without modification. Cannot be loaded simultaneously with the
 * audioreactive usermod.
 *
 * Activate via platformio.ini override:
 *   custom_usermods = msgeq7
 *
 * AI: below section was generated by an AI
 */

#include "wled.h"

#ifndef ARDUINO_ARCH_ESP32
#error "msgeq7 usermod requires ESP32"
#endif

// FFTsampleType must be defined before including audio_source.h, which uses it
// in its getSamples() virtual method signature.
using FFTsampleType = float;

// DEBUGSR_* macros are used throughout audio_source.h.
// Define them before the include; mirror audioreactive's SR_DEBUG pattern.
#ifdef SR_DEBUG
  #define DEBUGSR_PRINT(x)    DEBUGOUT.print(x)
  #define DEBUGSR_PRINTLN(x)  DEBUGOUT.println(x)
  #define DEBUGSR_PRINTF(...) DEBUGOUT.printf(__VA_ARGS__)
#else
  #define DEBUGSR_PRINT(x)
  #define DEBUGSR_PRINTLN(x)
  #define DEBUGSR_PRINTF(...)
#endif

#include "audio_source.h"

#include <dsps_biquad_gen.h>   // esp-dsp: coefficient generation
#include <dsps_biquad.h>       // esp-dsp: filter processing

// ─── Constants ───────────────────────────────────────────────────────────────

// Software backend sample rate. Must be ≥ 32000 Hz to represent the 16 kHz band.
// 44100 Hz is the standard CD audio rate and gives a comfortable margin above 16 kHz.
static constexpr SRate_t MSGEQ7_SAMPLE_RATE = 44100;

// I2S DMA block size (samples per read). Chosen to match audioreactive.
static constexpr int MSGEQ7_BLOCK_SIZE = 128;

// Number of MSGEQ7 frequency bands.
static constexpr int NUM_BANDS = 7;

// Number of GEQ output channels expected by WLED effects.
static constexpr int NUM_GEQ_CHANNELS = 16;

// Center frequencies of the 7 MSGEQ7 bandpass filters (Hz).
// Source: MSGEQ7 datasheet (Mixed Signal Integration MSI, Inc.).
static constexpr float MSGEQ7_FREQS_HZ[NUM_BANDS] = {
  63.0f, 160.0f, 400.0f, 1000.0f, 2500.0f, 6250.0f, 16000.0f
};

// Default filter Q (quality factor). Real MSGEQ7 bands are spaced by a factor
// of 2.5 (≈1.32 octaves) and overlap noticeably; the corresponding Q for
// non-overlapping bandpasses at this spacing is Q = sqrt(2^N)/(2^N − 1) ≈ 1.05
// with N = 1.32 octaves. Q = 1.0 closely matches the chip's response — slightly
// wider than 1.05 to give modest band overlap as the real chip exhibits.
static constexpr float MSGEQ7_DEFAULT_Q = 1.0f;

// Envelope detector time constants (seconds).
// Approximate real MSGEQ7 peak-hold behaviour: fast attack, slow decay.
static constexpr float MSGEQ7_ATTACK_SEC  = 0.015f;  // 15 ms attack
static constexpr float MSGEQ7_DECAY_SEC   = 0.080f;  // 80 ms decay

// Log compression: output = 255 * log10(1 + MSGEQ7_LOG_SCALE * normalised_input)
// MSGEQ7_LOG_SCALE = 9 maps linear 0..1 → compressed 0..1 with more low-signal
// resolution, matching the real chip's logarithmic output characteristic.
static constexpr float MSGEQ7_LOG_SCALE = 9.0f;

// FreeRTOS task settings for the software processing task.
static constexpr uint8_t  MSGEQ7_TASK_PRIORITY = 1;
static constexpr uint32_t MSGEQ7_TASK_STACK     = 3072;  // bytes

// Minimum ms between hardware MSGEQ7 chip reads. The chip needs ~36 µs per band
// strobe, so 20 ms gives ~50 Hz update rate which is plenty.
static constexpr uint32_t MSGEQ7_HW_READ_INTERVAL_MS = 20;

// Beat/peak detection: set samplePeak when the rate of rise of the sum of the
// two lowest bands exceeds this fraction of the current peak.
static constexpr float MSGEQ7_PEAK_RISE_THRESHOLD = 0.15f;

// ─── Global shared state (written by task/ISR, read by main loop) ────────────
// Protected conceptually by the single-writer/single-reader property:
// the processing task is the sole writer; loop() is the sole reader.
// A memory barrier via volatile is sufficient here — no mutex needed.

static volatile float    s_bandEnvelope[NUM_BANDS] = {};  // 0.0–255.0 per band
static volatile float    s_volumeSmth = 0.0f;
static volatile uint16_t s_volumeRaw  = 0;
static volatile float    s_FFT_MajorPeak = 1.0f;
static volatile float    s_my_magnitude  = 0.001f;
static volatile uint8_t  s_samplePeak    = 0;

// Written by effects, read by effects (via um_data pointers). These are
// intentionally writable from effect code (see audioreactive comment in setup()).
static uint8_t  s_maxVol = 31;
static uint8_t  s_binNum = 8;

// ─── Interpolation table: 7 MSGEQ7 bands → 16 GEQ channels ─────────────────
//
// Each of the 16 GEQ output channels is assigned a representative frequency
// derived from audioreactive's FFT bin groupings at 22050 Hz. We then locate
// the two bracketing MSGEQ7 bands and store a linear interpolation weight in
// log-frequency space.
//
// This table is computed once in setup() and used every loop iteration.

struct GEQInterp {
  uint8_t lo;   // lower MSGEQ7 band index
  uint8_t hi;   // upper MSGEQ7 band index (lo+1, clamped to NUM_BANDS-1)
  float   t;    // interpolation weight towards hi: output = lo*(1-t) + hi*t
};

static GEQInterp s_geqInterp[NUM_GEQ_CHANNELS];

// Representative center frequencies for the 16 GEQ channels (Hz).
// Derived from audioreactive's fftAddAvg() bin ranges at 22050 Hz / 512 bins
// (43.07 Hz per bin). Center = (from + to) / 2 * 43.07.
// Extended to the 44100 Hz range for channels 14-15.
static const float GEQ_TARGET_FREQS_HZ[NUM_GEQ_CHANNELS] = {
   64.6f,   107.7f,  172.3f,  258.4f,
  344.5f,   472.8f,  667.9f,  926.0f,
 1291.0f,  1829.7f, 2561.6f, 3638.3f,
 5229.9f,  7468.5f, 9117.0f, 12903.0f
};

// Precompute s_geqInterp[] from GEQ_TARGET_FREQS_HZ and MSGEQ7_FREQS_HZ.
// Must be called once before the first use of the interpolation table.
static void buildInterpolationTable(void) {
  // Use log10 scale so that equal perceptual frequency distances map linearly.
  float logBands[NUM_BANDS];
  for (int b = 0; b < NUM_BANDS; b++) {
    logBands[b] = log10f(MSGEQ7_FREQS_HZ[b]);
  }

  for (int ch = 0; ch < NUM_GEQ_CHANNELS; ch++) {
    float logTarget = log10f(GEQ_TARGET_FREQS_HZ[ch]);

    // Find the two MSGEQ7 bands that bracket this frequency in log space.
    int lo = 0;
    for (int b = 0; b < NUM_BANDS - 1; b++) {
      if (logBands[b] <= logTarget) lo = b;
    }
    int hi = lo + 1;
    if (hi >= NUM_BANDS) hi = NUM_BANDS - 1;

    float t = 0.0f;
    if (hi != lo) {
      t = (logTarget - logBands[lo]) / (logBands[hi] - logBands[lo]);
      // Clamp to [0,1] so out-of-range frequencies saturate at the nearest band.
      if (t < 0.0f) t = 0.0f;
      if (t > 1.0f) t = 1.0f;
    }

    s_geqInterp[ch].lo = (uint8_t)lo;
    s_geqInterp[ch].hi = (uint8_t)hi;
    s_geqInterp[ch].t  = t;
  }
}

// ─── Software backend: biquad filter chain ───────────────────────────────────

// esp-dsp biquad requires 16-byte-aligned coefficient and delay-line arrays
// when using the ae32/aes3 SIMD variants.
// Layout per filter: float coeffs[5]={b0,b1,b2,a1,a2}, float w[2]={w0,w1}.
// We store them together so each filter state is contiguous.

struct alignas(16) BandFilter {
  float coeffs[5];  // biquad coefficients produced by dsps_biquad_gen_bpf_f32()
  float w[2];       // IIR delay line (initialised to zero; written by filter)
};

static BandFilter s_filters[NUM_BANDS];

// Compute biquad coefficients for all 7 bands at the given Q and sample rate.
// Called from setup() and whenever Q changes.
static void initBiquadCoeffs(float sampleRate, float Q) {
  for (int b = 0; b < NUM_BANDS; b++) {
    // Normalised frequency for esp-dsp: f = fc / fs, expected range [0 .. 0.5].
    // The 16 kHz band at 44100 Hz gives f = 0.363 — well within range.
    float f = MSGEQ7_FREQS_HZ[b] / sampleRate;
    if (f >= 0.5f) f = 0.499f;  // hard clamp below Nyquist
    dsps_biquad_gen_bpf_f32(s_filters[b].coeffs, f, Q);
    s_filters[b].w[0] = 0.0f;
    s_filters[b].w[1] = 0.0f;
  }
}

// Compute one-pole attack/decay IIR coefficients from time constants.
// coeff = 1 - exp(-1 / (timeConst_s * sampleRate))
// For large timeConst the result is near 0 (slow); for small, near 1 (fast).
static float timeConstToCoeff(float timeConst_s, float sampleRate) {
  return 1.0f - expf(-1.0f / (timeConst_s * sampleRate));
}

// ─── Software processing task ────────────────────────────────────────────────
//
// Runs on Core 0 with MSGEQ7_TASK_PRIORITY.
// Reads I2S samples in blocks, runs each block through all 7 biquad filters,
// updates envelope detectors, and writes the results to the shared volatile
// state variables.

struct SWTaskParams {
  AudioSource *source;
  float        Q;
  float        gainLevel;      // linear multiplier applied to raw samples
  float        squelch;        // below this raw magnitude, force envelope to zero
  float        attackCoeff;    // computed from MSGEQ7_ATTACK_SEC
  float        decayCoeff;     // computed from MSGEQ7_DECAY_SEC
  volatile bool stop;          // set true to request task exit
};

static volatile TaskHandle_t s_swTaskHandle = nullptr;

// AI: below section was generated by an AI
static void IRAM_ATTR softwareProcessingTask(void *pvParams) {
  SWTaskParams *p = static_cast<SWTaskParams*>(pvParams);

  // Allocate working buffers on the task stack is too risky (3 KB stack).
  // Use heap instead.  Both buffers hold one I2S block.
  float *inputBuf   = static_cast<float*>(malloc(MSGEQ7_BLOCK_SIZE * sizeof(float)));
  float *filteredBuf = static_cast<float*>(malloc(MSGEQ7_BLOCK_SIZE * sizeof(float)));

  if (!inputBuf || !filteredBuf) {
    free(inputBuf);
    free(filteredBuf);
    vTaskDelete(nullptr);
    return;
  }

  float envelope[NUM_BANDS] = {};         // local copy, written back to shared state
  float prevLowBandSum = 0.0f;            // for peak (beat) detection
  float peakHoldTimer  = 0.0f;            // counts down to auto-clear samplePeak

  const TickType_t xFrequency = pdMS_TO_TICKS(1);  // yield every ms (WDT feed)

  while (!p->stop) {
    delay(1);  // feeds IDLE(0) watchdog — do not remove; see audioreactive comment

    if (!p->source || !p->source->isInitialized()) {
      vTaskDelay(xFrequency);
      continue;
    }

    // --- Read one block of audio samples from I2S DMA ---
    p->source->getSamples(inputBuf, MSGEQ7_BLOCK_SIZE);

    // --- Apply input gain and compute raw block peak (for volumeRaw) ---
    float blockPeak = 0.0f;
    float blockSumSq = 0.0f;
    for (int i = 0; i < MSGEQ7_BLOCK_SIZE; i++) {
      inputBuf[i] *= p->gainLevel;
      float absVal = fabsf(inputBuf[i]);
      if (absVal > blockPeak) blockPeak = absVal;
      blockSumSq += absVal * absVal;
    }
    float blockRMS = sqrtf(blockSumSq / MSGEQ7_BLOCK_SIZE);

    // --- Run each biquad bandpass filter over the block, update envelope ---
    for (int b = 0; b < NUM_BANDS; b++) {
      // Select the best available SIMD variant at compile time.
#if dsps_biquad_f32_aes3_enabled
      dsps_biquad_f32_aes3(inputBuf, filteredBuf, MSGEQ7_BLOCK_SIZE,
                            s_filters[b].coeffs, s_filters[b].w);
#elif dsps_biquad_f32_ae32_enabled
      dsps_biquad_f32_ae32(inputBuf, filteredBuf, MSGEQ7_BLOCK_SIZE,
                            s_filters[b].coeffs, s_filters[b].w);
#else
      dsps_biquad_f32_ansi(inputBuf, filteredBuf, MSGEQ7_BLOCK_SIZE,
                            s_filters[b].coeffs, s_filters[b].w);
#endif

      // Half-wave rectify (abs) then update peak-hold envelope.
      // Note: NO squelch here — squelch is applied to the compressed output
      // below, where the user-facing 0..255 scale lives.
      float attackC = p->attackCoeff;
      float decayC  = p->decayCoeff;
      float env = envelope[b];
      for (int i = 0; i < MSGEQ7_BLOCK_SIZE; i++) {
        float absVal = fabsf(filteredBuf[i]);
        if (absVal > env) {
          env += (absVal - env) * attackC;
        } else {
          env += (absVal - env) * decayC;
        }
      }
      envelope[b] = env;
    }

    // --- Log-compress envelopes to 0..255 ABSOLUTE scale ---
    // The real MSGEQ7 chip outputs an analog voltage proportional to the
    // peak-detected band amplitude — quiet sounds → small voltage, loud → large.
    // We therefore normalise against the full int16 sample range (a fixed
    // reference) — NOT against the per-frame band peak — so absolute amplitude
    // is preserved. This is what audioreactive's fftResult[] does and what
    // every WLED audio-reactive effect expects.
    //
    // Compression curve: out = 255 * log10(1 + 9*x) / log10(10), x = env/32768
    // Maps linear 0..1 → 0..255 with greater resolution at low levels, similar
    // to the chip's logarithmic output.
    static constexpr float kFullScale  = 32768.0f;       // float-int16 full range
    // Pre-computed log10(1 + MSGEQ7_LOG_SCALE) — used to normalise the curve so
    // a unity input maps to 255. Stays correct if MSGEQ7_LOG_SCALE is changed.
    const float kLogDivisor = log10f(1.0f + MSGEQ7_LOG_SCALE);
    float compressedEnv[NUM_BANDS];
    for (int b = 0; b < NUM_BANDS; b++) {
      float normalised = envelope[b] / kFullScale;       // 0..1+ (clamped below)
      if (normalised < 0.0f) normalised = 0.0f;
      if (normalised > 1.0f) normalised = 1.0f;
      float c = 255.0f * (log10f(1.0f + MSGEQ7_LOG_SCALE * normalised) / kLogDivisor);
      // Apply user-facing noise gate on the output 0..255 scale (matches UI).
      if (c < p->squelch) c = 0.0f;
      compressedEnv[b] = c;
    }

    // --- Beat / samplePeak detection ---
    // Detect a sudden rise in sub-bass energy (bands 0 and 1: 63 + 160 Hz).
    float lowBandSum = compressedEnv[0] + compressedEnv[1];
    float rise = lowBandSum - prevLowBandSum;
    if (rise > MSGEQ7_PEAK_RISE_THRESHOLD * 255.0f && lowBandSum > p->squelch) {
      s_samplePeak = 1;
      peakHoldTimer = 40.0f;  // hold for ~40 loop iterations (≈ 1 LED frame at 25fps)
    }
    prevLowBandSum = lowBandSum;
    if (peakHoldTimer > 0.0f) {
      peakHoldTimer -= 1.0f;
      if (peakHoldTimer <= 0.0f) s_samplePeak = 0;
    }

    // --- FFT_MajorPeak via parabolic interpolation of top-2 bands ---
    // Find the band with the highest compressed amplitude.
    int peakBand = 0;
    for (int b = 1; b < NUM_BANDS; b++) {
      if (compressedEnv[b] > compressedEnv[peakBand]) peakBand = b;
    }
    float majorPeak = MSGEQ7_FREQS_HZ[peakBand];
    // Parabolic interpolation using log-spaced frequencies smooths the
    // staircase artifact seen in FREQMAP/WATERFALL effects.
    if (peakBand > 0 && peakBand < NUM_BANDS - 1) {
      float a = compressedEnv[peakBand - 1];
      float b_val = compressedEnv[peakBand];
      float c = compressedEnv[peakBand + 1];
      float denom = a - 2.0f * b_val + c;
      if (fabsf(denom) > 1e-6f) {
        // Fractional offset in log-frequency space, range [-0.5, +0.5]
        float offset = 0.5f * (a - c) / denom;
        float logFreqLo = log10f(MSGEQ7_FREQS_HZ[peakBand > 0 ? peakBand - 1 : 0]);
        float logFreqHi = log10f(MSGEQ7_FREQS_HZ[peakBand < NUM_BANDS-1 ? peakBand + 1 : NUM_BANDS-1]);
        float logFreqPeak = log10f(MSGEQ7_FREQS_HZ[peakBand]);
        float step = (offset >= 0.0f) ? (logFreqHi - logFreqPeak) : (logFreqPeak - logFreqLo);
        majorPeak = powf(10.0f, logFreqPeak + offset * step);
      }
    }
    // Clamp to the range expected by effects (1 Hz .. Nyquist).
    if (majorPeak < 1.0f)                    majorPeak = 1.0f;
    if (majorPeak > MSGEQ7_SAMPLE_RATE / 2)  majorPeak = MSGEQ7_SAMPLE_RATE / 2;

    // --- my_magnitude: scaled peak band amplitude ---
    float magnitude = compressedEnv[peakBand] * p->gainLevel;
    if (magnitude < 0.001f) magnitude = 0.001f;

    // --- Volume from RMS and block peak ---
    // volumeSmth: smoothed RMS-based volume, scaled to 0..255 range.
    // Normalise by a typical maximum value then apply log compression.
    float normRMS = blockRMS / 32768.0f * p->gainLevel;  // float samples are ~[-32768..32768]
    float volSmth = 255.0f * (log10f(1.0f + MSGEQ7_LOG_SCALE * constrain(normRMS, 0.0f, 1.0f))
                               / log10f(1.0f + MSGEQ7_LOG_SCALE));
    uint16_t volRaw = (uint16_t)constrain(blockPeak * p->gainLevel / 128.0f, 0.0f, 65535.0f);

    // --- Debug output for sweep_analyze.py (compiled out unless SR_DEBUG) ---
#ifdef SR_DEBUG
    DEBUGSR_PRINTF("MSGEQ7 bands: 0=%d 1=%d 2=%d 3=%d 4=%d 5=%d 6=%d\n",
      (int)compressedEnv[0], (int)compressedEnv[1], (int)compressedEnv[2],
      (int)compressedEnv[3], (int)compressedEnv[4], (int)compressedEnv[5],
      (int)compressedEnv[6]);
#endif

    // --- Write to shared volatile state ---
    for (int b = 0; b < NUM_BANDS; b++) s_bandEnvelope[b] = compressedEnv[b];
    s_volumeSmth    = volSmth;
    s_volumeRaw     = volRaw;
    s_FFT_MajorPeak = majorPeak;
    s_my_magnitude  = magnitude;
    // s_samplePeak is written above
  }  // while (!p->stop)

  free(inputBuf);
  free(filteredBuf);
  // Signal _stopProcessing() that we have fully exited before the task is deleted.
  s_swTaskHandle = nullptr;
  vTaskDelete(nullptr);
}
// AI: end

// ─── MSGEQ7 Usermod class ─────────────────────────────────────────────────────

class MSGEQ7Usermod : public Usermod {

public:
  // ── Lifecycle ──────────────────────────────────────────────────────────────

  void setup() override {
    if (_initDone) return;

    // Allocate the um_data structure. Layout mirrors audioreactive exactly so
    // existing effects work without any modification.
    _umData = new um_data_t;
    _umData->u_size = 8;
    _umData->u_type = new um_types_t[_umData->u_size];
    _umData->u_data = new void*[_umData->u_size];

    _umData->u_data[0] = &_volumeSmth;       _umData->u_type[0] = UMT_FLOAT;
    _umData->u_data[1] = &_volumeRaw;        _umData->u_type[1] = UMT_UINT16;
    _umData->u_data[2] = _fftResult;         _umData->u_type[2] = UMT_BYTE_ARR;
    _umData->u_data[3] = &_samplePeak;       _umData->u_type[3] = UMT_BYTE;
    _umData->u_data[4] = &_FFT_MajorPeak;    _umData->u_type[4] = UMT_FLOAT;
    _umData->u_data[5] = &_my_magnitude;     _umData->u_type[5] = UMT_FLOAT;
    _umData->u_data[6] = &s_maxVol;          _umData->u_type[6] = UMT_BYTE;
    _umData->u_data[7] = &s_binNum;          _umData->u_type[7] = UMT_BYTE;

    buildInterpolationTable();
    _initDone = true;

    if (!_enabled) return;
    _startProcessing();
  }

  void loop() override {
    if (!_enabled) return;
    // Guard: be nice to LED refresh, same pattern as audioreactive
    if (strip.isUpdating() && (millis() - _lastLoopMs < 2)) return;
    _lastLoopMs = millis();

    if (_useHardwareChip) {
      _readHardwareChip();
    }

    // Copy shared volatile state into the um_data member variables.
    // This is the only place where the volatile→non-volatile copy happens,
    // keeping the effect read path simple.
    _volumeSmth    = s_volumeSmth;
    _volumeRaw     = s_volumeRaw;
    _FFT_MajorPeak = s_FFT_MajorPeak;
    _my_magnitude  = s_my_magnitude;
    _samplePeak    = s_samplePeak;

    // Build 16-channel fftResult[] from 7 MSGEQ7 band envelopes via precomputed
    // log-frequency interpolation table.
    for (int ch = 0; ch < NUM_GEQ_CHANNELS; ch++) {
      const GEQInterp &g = s_geqInterp[ch];
      float lo = s_bandEnvelope[g.lo];
      float hi = s_bandEnvelope[g.hi];
      float val = lo + g.t * (hi - lo);
      // Clamp and round to uint8_t (0..255).
      if (val < 0.0f)   val = 0.0f;
      if (val > 255.0f) val = 255.0f;
      _fftResult[ch] = (uint8_t)val;
    }
  }

  // ── um_data provider ───────────────────────────────────────────────────────

  bool getUMData(um_data_t **data) override {
    if (!_enabled || !_umData) return false;
    *data = _umData;
    return true;
  }

  // ── Identity ───────────────────────────────────────────────────────────────

  // Same ID as audioreactive so all existing effects use us transparently.
  uint16_t getId() override { return USERMOD_ID_AUDIOREACTIVE; }

  // ── Configuration persistence ──────────────────────────────────────────────

  void addToConfig(JsonObject &root) override {
    JsonObject top = root[FPSTR(_name)];
    if (top.isNull()) top = root.createNestedObject(FPSTR(_name));

    top[F("enabled")]    = _enabled;
    top[F("useHwChip")]  = _useHardwareChip;
    top[F("dmType")]     = _dmType;
    top[F("pinSD")]      = _pinSD;
    top[F("pinWS")]      = _pinWS;
    top[F("pinSCK")]     = _pinSCK;
    top[F("pinMCLK")]    = _pinMCLK;
    top[F("pinStrobe")]  = _pinStrobe;
    top[F("pinReset")]   = _pinReset;
    top[F("pinOut")]     = _pinOut;
    top[F("gain")]       = _gainPercent;
    top[F("squelch")]    = _squelchLevel;
    top[F("filterQ")]    = _filterQ;
    top[F("attackMs")]   = _attackMs;
    top[F("decayMs")]    = _decayMs;
  }

  bool readFromConfig(JsonObject &root) override {
    JsonObject top = root[FPSTR(_name)];
    if (top.isNull()) return false;

    bool changed = false;
    bool newEnabled    = top[F("enabled")]   | _enabled;
    bool newUseHwChip  = top[F("useHwChip")] | _useHardwareChip;
    uint8_t newDmType  = top[F("dmType")]    | _dmType;
    int8_t  newPinSD   = top[F("pinSD")]     | _pinSD;
    int8_t  newPinWS   = top[F("pinWS")]     | _pinWS;
    int8_t  newPinSCK  = top[F("pinSCK")]    | _pinSCK;
    int8_t  newPinMCLK = top[F("pinMCLK")]   | _pinMCLK;
    int8_t  newStrobe  = top[F("pinStrobe")] | _pinStrobe;
    int8_t  newReset   = top[F("pinReset")]  | _pinReset;
    int8_t  newOut     = top[F("pinOut")]    | _pinOut;
    uint8_t newGain    = top[F("gain")]      | _gainPercent;
    uint8_t newSqlch   = top[F("squelch")]   | _squelchLevel;
    float   newQ       = top[F("filterQ")]   | _filterQ;
    uint16_t newAtk    = top[F("attackMs")]  | _attackMs;
    uint16_t newDec    = top[F("decayMs")]   | _decayMs;

    // Any hardware/filter change needs a full reinit.
    if (newEnabled != _enabled || newUseHwChip != _useHardwareChip
        || newDmType != _dmType || newPinSD != _pinSD || newPinWS != _pinWS
        || newPinSCK != _pinSCK || newPinMCLK != _pinMCLK
        || newStrobe != _pinStrobe || newReset != _pinReset || newOut != _pinOut
        || newQ != _filterQ) {
      changed = true;
    }

    _enabled          = newEnabled;
    _useHardwareChip  = newUseHwChip;
    _dmType           = newDmType;
    _pinSD            = newPinSD;
    _pinWS            = newPinWS;
    _pinSCK           = newPinSCK;
    _pinMCLK          = newPinMCLK;
    _pinStrobe        = newStrobe;
    _pinReset         = newReset;
    _pinOut           = newOut;
    _gainPercent      = newGain;
    _squelchLevel     = newSqlch;
    _filterQ          = newQ;
    _attackMs         = newAtk;
    _decayMs          = newDec;

    if (changed && _initDone) {
      _stopProcessing();
      if (_enabled) _startProcessing();
    }

    return true;
  }

  void appendConfigData() override {
    // Append UI helpers via the settings page JS API.
    // Labels and select options for dmType, matching audioreactive's mic types.
    oappend(SET_F("addInfo('MSGEQ7:dmType',1,'<i>(software backend)</i>');"));
    oappend(SET_F("dd=addDropdown('MSGEQ7','dmType');"));
    oappend(SET_F("addOption(dd,'Generic I2S',1);"));
    oappend(SET_F("addOption(dd,'ES7243',2);"));
    oappend(SET_F("addOption(dd,'SPH0645',3);"));
    oappend(SET_F("addOption(dd,'I2S + MCLK',4);"));
    oappend(SET_F("addOption(dd,'PDM',5);"));
    oappend(SET_F("addOption(dd,'ES8388',6);"));
    oappend(SET_F("addOption(dd,'ADC (classic ESP32)',0);"));
  }

  // ── Info page ──────────────────────────────────────────────────────────────

  void addToJsonInfo(JsonObject &root) override {
    JsonObject user = root[F("u")];
    if (user.isNull()) user = root.createNestedObject(F("u"));
    JsonArray arr = user.createNestedArray(F("MSGEQ7"));
    if (!_enabled) {
      arr.add(F("disabled"));
      return;
    }
    const char *backend = _useHardwareChip ? "hw chip" : "sw emulation";
    arr.add(backend);
  }

private:
  // ── Private methods ────────────────────────────────────────────────────────

  void _startProcessing() {
    if (_useHardwareChip) {
      _initHardwareChip();
    } else {
      _initSoftwareBackend();
    }
  }

  void _stopProcessing() {
    if (!_useHardwareChip && s_swTaskHandle) {
      // Signal the task to stop and wait for it to exit.
      if (_swTaskParams) _swTaskParams->stop = true;
      // Give the task up to 500ms to terminate gracefully.
      uint32_t deadline = millis() + 500;
      while (s_swTaskHandle != nullptr && millis() < deadline) delay(10);
      s_swTaskHandle = nullptr;
    }
    if (_swTaskParams) {
      delete _swTaskParams;
      _swTaskParams = nullptr;
    }
    if (_audioSource) {
      _audioSource->deinitialize();
      delete _audioSource;
      _audioSource = nullptr;
    }
    _deinitHardwareChip();

    // Zero out shared state so effects don't see stale data after disable.
    for (int b = 0; b < NUM_BANDS; b++) s_bandEnvelope[b] = 0.0f;
    s_volumeSmth    = 0.0f;
    s_volumeRaw     = 0;
    s_FFT_MajorPeak = 1.0f;
    s_my_magnitude  = 0.001f;
    s_samplePeak    = 0;
  }

  // ── Software backend initialisation ──────────────────────────────────────

  void _initSoftwareBackend() {
    // Reset I2S peripheral (follows audioreactive pattern).
    i2s_driver_uninstall(I2S_NUM_0);
#if !defined(CONFIG_IDF_TARGET_ESP32C3)
    delay(100);
    periph_module_reset(PERIPH_I2S0_MODULE);
#endif
    delay(100);

    // Infer PDM from missing SCK pin on dmType 1 and 4 (same heuristic as AR).
#if !defined(CONFIG_IDF_TARGET_ESP32S2) && !defined(CONFIG_IDF_TARGET_ESP32C3)
    if ((_pinSCK == I2S_PIN_NO_CHANGE) && (_pinSD >= 0) && (_pinWS >= 0)
        && ((_dmType == 1) || (_dmType == 4))) {
      _dmType = 5;
    }
#endif

    switch (_dmType) {
#if defined(CONFIG_IDF_TARGET_ESP32S2) || defined(CONFIG_IDF_TARGET_ESP32C3) || defined(CONFIG_IDF_TARGET_ESP32S3)
      case 0: // ADC — not supported on S2/C3/S3
#if defined(CONFIG_IDF_TARGET_ESP32S2) || defined(CONFIG_IDF_TARGET_ESP32C3)
      case 5: // PDM — not supported on S2/C3
#endif
#endif
      case 1:
        _audioSource = new I2SSource(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD, _pinSCK);
        break;
      case 2:
        _audioSource = new ES7243(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD, _pinSCK, _pinMCLK);
        break;
      case 3:
        _audioSource = new SPH0654(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD, _pinSCK);
        break;
      case 4:
        // I2S with MCLK (line-in boards). Scale factor 1/24 matches audioreactive.
        _audioSource = new I2SSource(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE, 1.0f/24.0f);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD, _pinSCK, _pinMCLK);
        break;
#if !defined(CONFIG_IDF_TARGET_ESP32S2) && !defined(CONFIG_IDF_TARGET_ESP32C3)
      case 5:
        _audioSource = new I2SSource(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE, 1.0f/4.0f);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD);
        break;
#endif
      case 6:
        _audioSource = new ES8388Source(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD, _pinSCK, _pinMCLK);
        break;
#if !defined(CONFIG_IDF_TARGET_ESP32S2) && !defined(CONFIG_IDF_TARGET_ESP32C3) && !defined(CONFIG_IDF_TARGET_ESP32S3)
      case 0:
        _audioSource = new I2SAdcSource(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinSD);
        break;
#endif
      default:
        DEBUG_PRINTLN(F("MSGEQ7: unknown dmType"));
        return;
    }

    if (!_audioSource || !_audioSource->isInitialized()) {
      DEBUG_PRINTLN(F("MSGEQ7: audio source init failed"));
      if (_audioSource) { delete _audioSource; _audioSource = nullptr; }
      return;
    }

    // Compute biquad coefficients for all 7 bands.
    initBiquadCoeffs((float)MSGEQ7_SAMPLE_RATE, _filterQ);

    // Compute envelope coefficients from ms time constants and the block rate.
    // The envelope is updated once per sample (not per block), so use sample rate.
    float attackC = timeConstToCoeff(_attackMs * 0.001f, (float)MSGEQ7_SAMPLE_RATE);
    float decayC  = timeConstToCoeff(_decayMs  * 0.001f, (float)MSGEQ7_SAMPLE_RATE);
    float linearGain = (_gainPercent / 128.0f);  // 128 = unity gain

    _swTaskParams = new SWTaskParams{
      /*.source      =*/ _audioSource,
      /*.Q           =*/ _filterQ,
      /*.gainLevel   =*/ linearGain,
      /*.squelch     =*/ (float)_squelchLevel,
      /*.attackCoeff =*/ attackC,
      /*.decayCoeff  =*/ decayC,
      /*.stop        =*/ false
    };

    // xTaskCreatePinnedToCore requires a non-volatile TaskHandle_t*.
    // Write through a temporary then store to the volatile handle.
    TaskHandle_t handle = nullptr;
    xTaskCreatePinnedToCore(
      softwareProcessingTask,
      "MSGEQ7",
      MSGEQ7_TASK_STACK,
      _swTaskParams,
      MSGEQ7_TASK_PRIORITY,
      &handle,
      0  // Core 0, same as audioreactive FFT task
    );
    s_swTaskHandle = handle;
  }

  // ── Hardware MSGEQ7 chip backend ──────────────────────────────────────────

  void _initHardwareChip() {
    if (_pinStrobe < 0 || _pinReset < 0 || _pinOut < 0) {
      DEBUG_PRINTLN(F("MSGEQ7: hw chip pins not configured"));
      return;
    }
    if (!PinManager::allocatePin(_pinStrobe, true,  PinOwner::UM_Audioreactive)
     || !PinManager::allocatePin(_pinReset,  true,  PinOwner::UM_Audioreactive)
     || !PinManager::allocatePin(_pinOut,    false, PinOwner::UM_Audioreactive)) {
      DEBUG_PRINTLN(F("MSGEQ7: failed to allocate hw chip pins"));
      _deinitHardwareChip();
      return;
    }
    pinMode(_pinStrobe, OUTPUT);
    pinMode(_pinReset,  OUTPUT);
    // OUT is analog input — configure via analogRead (no pinMode needed)
    digitalWrite(_pinStrobe, HIGH);
    digitalWrite(_pinReset,  LOW);
    _hwChipReady = true;
  }

  void _deinitHardwareChip() {
    if (_hwChipReady) {
      PinManager::deallocatePin(_pinStrobe, PinOwner::UM_Audioreactive);
      PinManager::deallocatePin(_pinReset,  PinOwner::UM_Audioreactive);
      PinManager::deallocatePin(_pinOut,    PinOwner::UM_Audioreactive);
      _hwChipReady = false;
    }
  }

  // Read all 7 bands from the physical MSGEQ7 chip.
  // The chip outputs band amplitudes one at a time as an analog voltage.
  // Protocol (from MSGEQ7 datasheet):
  //   1. Pulse RESET high for ≥100ns to reset the internal mux to band 0.
  //   2. For each band: pull STROBE low, wait ≥36 µs, read OUT, pull STROBE high.
  //   3. Repeat step 2 for all 7 bands (the mux auto-advances on each strobe).
  void _readHardwareChip() {
    if (!_hwChipReady) return;
    uint32_t now = millis();
    if (now - _lastHwReadMs < MSGEQ7_HW_READ_INTERVAL_MS) return;
    _lastHwReadMs = now;

    // Reset internal mux to band 0.
    digitalWrite(_pinReset, HIGH);
    delayMicroseconds(1);
    digitalWrite(_pinReset, LOW);
    delayMicroseconds(72);  // allow output to settle after reset

    float linearGain = (_gainPercent / 128.0f);
    float squelch    = (float)_squelchLevel;
    float prevLow    = s_bandEnvelope[0] + s_bandEnvelope[1];

    for (int b = 0; b < NUM_BANDS; b++) {
      digitalWrite(_pinStrobe, LOW);
      delayMicroseconds(36);                          // strobe-to-output delay (Tso)
      uint16_t adcVal = analogRead(_pinOut);          // 12-bit ADC: 0..4095
      digitalWrite(_pinStrobe, HIGH);
      delayMicroseconds(36);                          // hold before next strobe (Tsh ≥ 18µs)

      // Scale 12-bit ADC (0..4095) to 0..255 using the full ADC resolution
      // before truncating, then apply user gain. Avoids the 4-bit precision
      // loss of `>>4` — small differences near the noise floor stay visible.
      float val = (adcVal * (255.0f / 4095.0f)) * linearGain;
      if (val < squelch)   val = 0.0f;
      if (val > 255.0f)    val = 255.0f;
      s_bandEnvelope[b] = val;
    }

    // Hardware chip output is already log-compressed (analog voltage from chip).
    // Compute derived values from the band data.
    float envSum  = 0.0f;
    float envPeak = 0.0f;
    int   peakBand = 0;
    for (int b = 0; b < NUM_BANDS; b++) {
      float v = s_bandEnvelope[b];
      envSum += v;
      if (v > envPeak) { envPeak = v; peakBand = b; }
    }

    // volumeSmth: weighted sum of all bands, normalised.
    float volSmth = envSum / (float)NUM_BANDS;
    s_volumeSmth    = volSmth;
    s_volumeRaw     = (uint16_t)constrain(envPeak, 0.0f, 65535.0f);
    s_my_magnitude  = envPeak > 0.001f ? envPeak : 0.001f;

    // FFT_MajorPeak with parabolic interpolation (same as software path).
    float majorPeak = MSGEQ7_FREQS_HZ[peakBand];
    if (peakBand > 0 && peakBand < NUM_BANDS - 1) {
      float a = s_bandEnvelope[peakBand - 1];
      float b_v = s_bandEnvelope[peakBand];
      float c = s_bandEnvelope[peakBand + 1];
      float denom = a - 2.0f * b_v + c;
      if (fabsf(denom) > 1e-6f) {
        float offset = 0.5f * (a - c) / denom;
        float logLo  = log10f(MSGEQ7_FREQS_HZ[peakBand > 0 ? peakBand-1 : 0]);
        float logHi  = log10f(MSGEQ7_FREQS_HZ[peakBand < NUM_BANDS-1 ? peakBand+1 : NUM_BANDS-1]);
        float logPk  = log10f(MSGEQ7_FREQS_HZ[peakBand]);
        float step   = (offset >= 0.0f) ? (logHi - logPk) : (logPk - logLo);
        majorPeak    = powf(10.0f, logPk + offset * step);
      }
    }
    if (majorPeak < 1.0f) majorPeak = 1.0f;
    s_FFT_MajorPeak = majorPeak;

    // Beat detection on low bands.
    float lowSum = s_bandEnvelope[0] + s_bandEnvelope[1];
    if ((lowSum - prevLow) > MSGEQ7_PEAK_RISE_THRESHOLD * 255.0f && lowSum > squelch) {
      s_samplePeak = 1;
    } else {
      s_samplePeak = 0;
    }
  }

  // ── Member variables ───────────────────────────────────────────────────────

  // um_data output variables (these are the actual values effects read via pointers)
  float    _volumeSmth    = 0.0f;
  uint16_t _volumeRaw     = 0;
  uint8_t  _fftResult[NUM_GEQ_CHANNELS] = {};
  uint8_t  _samplePeak    = 0;
  float    _FFT_MajorPeak = 1.0f;
  float    _my_magnitude  = 0.001f;

  // um_data container
  um_data_t *_umData = nullptr;

  // Audio source (software backend only)
  AudioSource *_audioSource = nullptr;

  // FreeRTOS task params (software backend)
  SWTaskParams *_swTaskParams = nullptr;

  // Settings
  bool     _enabled         = false;
  bool     _useHardwareChip = false;
  uint8_t  _dmType          = 1;         // 1 = Generic I2S (default)
  int8_t   _pinSD           = I2S_PIN_NO_CHANGE;
  int8_t   _pinWS           = I2S_PIN_NO_CHANGE;
  int8_t   _pinSCK          = I2S_PIN_NO_CHANGE;
  int8_t   _pinMCLK         = I2S_PIN_NO_CHANGE;
  int8_t   _pinStrobe       = -1;
  int8_t   _pinReset        = -1;
  int8_t   _pinOut          = -1;
  uint8_t  _gainPercent     = 128;       // 128 = unity gain
  uint8_t  _squelchLevel    = 10;        // noise gate on 0..255 output scale
  float    _filterQ         = MSGEQ7_DEFAULT_Q;
  uint16_t _attackMs        = 15;
  uint16_t _decayMs         = 80;

  // State flags
  bool     _initDone      = false;
  bool     _hwChipReady   = false;
  uint32_t _lastHwReadMs  = 0;
  uint32_t _lastLoopMs    = 0;

  // PROGMEM key for config JSON
  static const char _name[];
};

const char MSGEQ7Usermod::_name[] PROGMEM = "MSGEQ7";

// ─── Registration ─────────────────────────────────────────────────────────────

static MSGEQ7Usermod msgeq7_usermod;
REGISTER_USERMOD(msgeq7_usermod);

// AI: end
