/*
 * msgeq7.cpp — WLED usermod wrapper for the MSGEQ7 audio-reactive engine
 *
 * Thin integration layer connecting the MSGEQ7 DSP engine (msgeq7_engine.h)
 * to the WLED usermod API. Responsible for:
 *   - AudioSource initialisation (I2S / ADC driver setup via audio_source.h)
 *   - GPIO pin reservation via WLED's PinManager
 *   - um_data_t registration so audio-reactive effects can consume the data
 *   - Settings persistence (JSON config, web UI helpers)
 *
 * All signal processing and hardware protocol code lives in msgeq7_engine.h.
 *
 * Registers as USERMOD_ID_AUDIOREACTIVE (32) so all existing audio-reactive
 * effects work without modification. Cannot be loaded simultaneously with the
 * audioreactive usermod.
 *
 * Activate via platformio.ini override:
 *   custom_usermods = msgeq7
 *
 * AI: below section was generated by an AI
 */

#include "wled.h"

#ifndef ARDUINO_ARCH_ESP32
#error "msgeq7 usermod requires ESP32"
#endif

// FFTsampleType must be defined before including audio_source.h, which uses it
// in its getSamples() virtual method signature.
using FFTsampleType = float;

// DEBUGSR_* macros are used throughout audio_source.h.
// Define them before the include; mirror audioreactive's SR_DEBUG pattern.
#ifdef SR_DEBUG
  #define DEBUGSR_PRINT(x)    DEBUGOUT.print(x)
  #define DEBUGSR_PRINTLN(x)  DEBUGOUT.println(x)
  #define DEBUGSR_PRINTF(...) DEBUGOUT.printf(__VA_ARGS__)
#else
  #define DEBUGSR_PRINT(x)
  #define DEBUGSR_PRINTLN(x)
  #define DEBUGSR_PRINTF(...)
#endif

#include "audio_source.h"
#include "msgeq7_engine.h"

// ─── MSGEQ7 Usermod ───────────────────────────────────────────────────────────

class MSGEQ7Usermod : public Usermod {

public:
  // ── Lifecycle ──────────────────────────────────────────────────────────────

  void setup() override {
    if (_initDone) return;

    // Allocate um_data matching audioreactive's exact 8-slot layout so all
    // audio-reactive effects work without modification.
    _umData = new um_data_t;
    _umData->u_size = 8;
    _umData->u_type = new um_types_t[_umData->u_size];
    _umData->u_data = new void*[_umData->u_size];

    _umData->u_data[0] = &_volumeSmth;    _umData->u_type[0] = UMT_FLOAT;
    _umData->u_data[1] = &_volumeRaw;     _umData->u_type[1] = UMT_UINT16;
    _umData->u_data[2] = _fftResult;      _umData->u_type[2] = UMT_BYTE_ARR;
    _umData->u_data[3] = &_samplePeak;    _umData->u_type[3] = UMT_BYTE;
    _umData->u_data[4] = &_FFT_MajorPeak; _umData->u_type[4] = UMT_FLOAT;
    _umData->u_data[5] = &_my_magnitude;  _umData->u_type[5] = UMT_FLOAT;
    _umData->u_data[6] = &s_maxVol;       _umData->u_type[6] = UMT_BYTE;
    _umData->u_data[7] = &s_binNum;       _umData->u_type[7] = UMT_BYTE;

    buildInterpolationTable();
    _initDone = true;

    if (!_enabled) return;
    _startProcessing();
  }

  void loop() override {
    if (!_enabled) return;
    // Guard: be nice to LED refresh, same pattern as audioreactive.
    if (strip.isUpdating() && (millis() - _lastLoopMs < 2)) return;
    _lastLoopMs = millis();

    if (_useHardwareChip) {
      _readHardwareChip();
    }

    // Copy shared volatile output state into the um_data member variables.
    // This is the only place where the volatile → non-volatile copy happens,
    // keeping the effect read path simple.
    _volumeSmth    = s_volumeSmth;
    _volumeRaw     = s_volumeRaw;
    _FFT_MajorPeak = s_FFT_MajorPeak;
    _my_magnitude  = s_my_magnitude;
    _samplePeak    = s_samplePeak;

    // Expand 7 MSGEQ7 bands to 16 GEQ channels via the precomputed
    // log-frequency interpolation table (built in buildInterpolationTable).
    for (int ch = 0; ch < NUM_GEQ_CHANNELS; ch++) {
      const GEQInterp &g = s_geqInterp[ch];
      float val = s_bandEnvelope[g.lo] + g.t * (s_bandEnvelope[g.hi] - s_bandEnvelope[g.lo]);
      if (val < 0.0f)   val = 0.0f;
      if (val > 255.0f) val = 255.0f;
      _fftResult[ch] = (uint8_t)val;
    }
  }

  // ── um_data provider ───────────────────────────────────────────────────────

  bool getUMData(um_data_t **data) override {
    if (!_enabled || !_umData) return false;
    *data = _umData;
    return true;
  }

  // ── Identity ───────────────────────────────────────────────────────────────

  // Same ID as audioreactive so all existing effects use us transparently.
  uint16_t getId() override { return USERMOD_ID_AUDIOREACTIVE; }

  // ── Configuration persistence ──────────────────────────────────────────────

  void addToConfig(JsonObject &root) override {
    JsonObject top = root[FPSTR(_name)];
    if (top.isNull()) top = root.createNestedObject(FPSTR(_name));

    top[F("enabled")]    = _enabled;
    top[F("useHwChip")]  = _useHardwareChip;
    top[F("dmType")]     = _dmType;
    top[F("pinSD")]      = _pinSD;
    top[F("pinWS")]      = _pinWS;
    top[F("pinSCK")]     = _pinSCK;
    top[F("pinMCLK")]    = _pinMCLK;
    top[F("pinStrobe")]  = _pinStrobe;
    top[F("pinReset")]   = _pinReset;
    top[F("pinOut")]     = _pinOut;
    top[F("gain")]       = _gainPercent;
    top[F("squelch")]    = _squelchLevel;
    top[F("filterQ")]    = _filterQ;
    top[F("attackMs")]   = _attackMs;
    top[F("decayMs")]    = _decayMs;
  }

  bool readFromConfig(JsonObject &root) override {
    JsonObject top = root[FPSTR(_name)];
    if (top.isNull()) return false;

    bool     newEnabled    = top[F("enabled")]   | _enabled;
    bool     newUseHwChip  = top[F("useHwChip")] | _useHardwareChip;
    uint8_t  newDmType     = top[F("dmType")]    | _dmType;
    int8_t   newPinSD      = top[F("pinSD")]     | _pinSD;
    int8_t   newPinWS      = top[F("pinWS")]     | _pinWS;
    int8_t   newPinSCK     = top[F("pinSCK")]    | _pinSCK;
    int8_t   newPinMCLK    = top[F("pinMCLK")]   | _pinMCLK;
    int8_t   newStrobe     = top[F("pinStrobe")] | _pinStrobe;
    int8_t   newReset      = top[F("pinReset")]  | _pinReset;
    int8_t   newOut        = top[F("pinOut")]    | _pinOut;
    uint8_t  newGain       = top[F("gain")]      | _gainPercent;
    uint8_t  newSqlch      = top[F("squelch")]   | _squelchLevel;
    float    newQ          = top[F("filterQ")]   | _filterQ;
    uint16_t newAtk        = top[F("attackMs")]  | _attackMs;
    uint16_t newDec        = top[F("decayMs")]   | _decayMs;

    // Any hardware or filter change requires a full reinitialisation.
    bool changed = (newEnabled != _enabled || newUseHwChip != _useHardwareChip
                    || newDmType != _dmType || newPinSD != _pinSD || newPinWS != _pinWS
                    || newPinSCK != _pinSCK || newPinMCLK != _pinMCLK
                    || newStrobe != _pinStrobe || newReset != _pinReset || newOut != _pinOut
                    || newQ != _filterQ);

    _enabled         = newEnabled;
    _useHardwareChip = newUseHwChip;
    _dmType          = newDmType;
    _pinSD           = newPinSD;
    _pinWS           = newPinWS;
    _pinSCK          = newPinSCK;
    _pinMCLK         = newPinMCLK;
    _pinStrobe       = newStrobe;
    _pinReset        = newReset;
    _pinOut          = newOut;
    _gainPercent     = newGain;
    _squelchLevel    = newSqlch;
    _filterQ         = newQ;
    _attackMs        = newAtk;
    _decayMs         = newDec;

    if (changed && _initDone) {
      _stopProcessing();
      if (_enabled) _startProcessing();
    }

    return true;
  }

  void appendConfigData() override {
    // Labels and select options for dmType, matching audioreactive's mic types.
    oappend(SET_F("addInfo('MSGEQ7:dmType',1,'<i>(software backend)</i>');"));
    oappend(SET_F("dd=addDropdown('MSGEQ7','dmType');"));
    oappend(SET_F("addOption(dd,'Generic I2S',1);"));
    oappend(SET_F("addOption(dd,'ES7243',2);"));
    oappend(SET_F("addOption(dd,'SPH0645',3);"));
    oappend(SET_F("addOption(dd,'I2S + MCLK',4);"));
    oappend(SET_F("addOption(dd,'PDM',5);"));
    oappend(SET_F("addOption(dd,'ES8388',6);"));
    oappend(SET_F("addOption(dd,'ADC (classic ESP32)',0);"));
  }

  // ── Info page ──────────────────────────────────────────────────────────────

  void addToJsonInfo(JsonObject &root) override {
    JsonObject user = root[F("u")];
    if (user.isNull()) user = root.createNestedObject(F("u"));
    JsonArray arr = user.createNestedArray(F("MSGEQ7"));
    if (!_enabled) { arr.add(F("disabled")); return; }
    arr.add(_useHardwareChip ? F("hw chip") : F("sw emulation"));
  }

private:
  // ── Backend lifecycle ──────────────────────────────────────────────────────

  void _startProcessing() {
    if (_useHardwareChip) _initHardwareChip();
    else                  _initSoftwareBackend();
  }

  void _stopProcessing() {
    // Stop the SW task regardless of the current _useHardwareChip value:
    // readFromConfig() updates _useHardwareChip BEFORE calling here, so
    // checking it would silently skip teardown on a SW→HW mode switch.
    if (s_swTaskHandle) {
      if (_swTaskParams) _swTaskParams->stop = true;
      uint32_t deadline = millis() + 500;
      while (s_swTaskHandle != nullptr && millis() < deadline) delay(10);
      if (s_swTaskHandle != nullptr) {
        // I2S stall: task didn't exit within 500 ms. Leak params and source
        // rather than freeing memory the still-running task has a pointer to.
        DEBUG_PRINTLN(F("MSGEQ7: SW task did not exit in 500ms; leaking params"));
        _swTaskParams  = nullptr;
        _audioSource   = nullptr;  // skip delete below
        s_swTaskHandle = nullptr;
      }
    }
    if (_swTaskParams) {
      delete _swTaskParams;
      _swTaskParams = nullptr;
    }
    if (_audioSource) {
      _audioSource->deinitialize();
      delete _audioSource;
      _audioSource = nullptr;
    }
    _deinitHardwareChip();

    // Zero shared state so effects don't see stale data after disable.
    for (int b = 0; b < NUM_BANDS; b++) s_bandEnvelope[b] = 0.0f;
    s_volumeSmth    = 0.0f;
    s_volumeRaw     = 0;
    s_FFT_MajorPeak = 1.0f;
    s_my_magnitude  = 0.001f;
    s_samplePeak    = 0;
  }

  // ── Software backend: AudioSource creation + task spawn ───────────────────
  //
  // Creates the correct AudioSource subclass for the configured microphone
  // type (I2S, PDM, ES7243, SPH0645, ES8388, ADC), initialises the biquad
  // filter coefficients, and spawns the softwareProcessingTask from
  // msgeq7_engine.h.

  void _initSoftwareBackend() {
    // Reset I2S peripheral (follows audioreactive pattern).
    i2s_driver_uninstall(I2S_NUM_0);
#if !defined(CONFIG_IDF_TARGET_ESP32C3)
    delay(100);
    periph_module_reset(PERIPH_I2S0_MODULE);
#endif
    delay(100);

    // Infer PDM from missing SCK on generic I2S types (matches audioreactive).
#if !defined(CONFIG_IDF_TARGET_ESP32S2) && !defined(CONFIG_IDF_TARGET_ESP32C3)
    if ((_pinSCK == I2S_PIN_NO_CHANGE) && (_pinSD >= 0) && (_pinWS >= 0)
        && ((_dmType == 1) || (_dmType == 4))) {
      _dmType = 5;
    }
#endif

    switch (_dmType) {
#if defined(CONFIG_IDF_TARGET_ESP32S2) || defined(CONFIG_IDF_TARGET_ESP32C3) || defined(CONFIG_IDF_TARGET_ESP32S3)
      case 0:  // ADC not supported on S2/C3/S3
#if defined(CONFIG_IDF_TARGET_ESP32S2) || defined(CONFIG_IDF_TARGET_ESP32C3)
      case 5:  // PDM not supported on S2/C3
#endif
#endif
      case 1:
        _audioSource = new I2SSource(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD, _pinSCK);
        break;
      case 2:
        _audioSource = new ES7243(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD, _pinSCK, _pinMCLK);
        break;
      case 3:
        _audioSource = new SPH0654(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD, _pinSCK);
        break;
      case 4:
        // I2S with MCLK (line-in boards). Scale factor 1/24 matches audioreactive.
        _audioSource = new I2SSource(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE, 1.0f/24.0f);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD, _pinSCK, _pinMCLK);
        break;
#if !defined(CONFIG_IDF_TARGET_ESP32S2) && !defined(CONFIG_IDF_TARGET_ESP32C3)
      case 5:
        _audioSource = new I2SSource(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE, 1.0f/4.0f);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD);
        break;
#endif
      case 6:
        _audioSource = new ES8388Source(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinWS, _pinSD, _pinSCK, _pinMCLK);
        break;
#if !defined(CONFIG_IDF_TARGET_ESP32S2) && !defined(CONFIG_IDF_TARGET_ESP32C3) && !defined(CONFIG_IDF_TARGET_ESP32S3)
      case 0:
        _audioSource = new I2SAdcSource(MSGEQ7_SAMPLE_RATE, MSGEQ7_BLOCK_SIZE);
        delay(100);
        if (_audioSource) _audioSource->initialize(_pinSD);
        break;
#endif
      default:
        DEBUG_PRINTLN(F("MSGEQ7: unknown dmType"));
        return;
    }

    if (!_audioSource || !_audioSource->isInitialized()) {
      DEBUG_PRINTLN(F("MSGEQ7: audio source init failed"));
      if (_audioSource) { delete _audioSource; _audioSource = nullptr; }
      return;
    }

    // Compute biquad coefficients for all 7 bands.
    initBiquadCoeffs((float)MSGEQ7_SAMPLE_RATE, _filterQ);

    // Compute envelope time-constant coefficients from ms settings.
    // Envelope is updated per sample, so use the sample rate here.
    float attackC    = timeConstToCoeff(_attackMs * 0.001f, (float)MSGEQ7_SAMPLE_RATE);
    float decayC     = timeConstToCoeff(_decayMs  * 0.001f, (float)MSGEQ7_SAMPLE_RATE);
    float linearGain = _gainPercent / 128.0f;

    _swTaskParams = new SWTaskParams{
      /*.source      =*/ _audioSource,
      /*.Q           =*/ _filterQ,
      /*.gainLevel   =*/ linearGain,
      /*.squelch     =*/ (float)_squelchLevel,
      /*.attackCoeff =*/ attackC,
      /*.decayCoeff  =*/ decayC,
      /*.stop        =*/ false
    };

    // xTaskCreatePinnedToCore requires a non-volatile TaskHandle_t*.
    // Write through a temporary then store to the volatile handle.
    TaskHandle_t handle = nullptr;
    xTaskCreatePinnedToCore(
      softwareProcessingTask,
      "MSGEQ7",
      MSGEQ7_TASK_STACK,
      _swTaskParams,
      MSGEQ7_TASK_PRIORITY,
      &handle,
      0  // Core 0, same as audioreactive FFT task
    );
    s_swTaskHandle = handle;
  }

  // ── Hardware MSGEQ7 chip backend ──────────────────────────────────────────
  //
  // PinManager is WLED-specific, so pin allocation/deallocation lives here.
  // The GPIO protocol and ADC read loop live in msgeq7_engine.h.

  void _initHardwareChip() {
    if (_pinStrobe < 0 || _pinReset < 0 || _pinOut < 0) {
      DEBUG_PRINTLN(F("MSGEQ7: hw chip pins not configured"));
      return;
    }
    if (!PinManager::allocatePin(_pinStrobe, true,  PinOwner::UM_Audioreactive)
     || !PinManager::allocatePin(_pinReset,  true,  PinOwner::UM_Audioreactive)
     || !PinManager::allocatePin(_pinOut,    false, PinOwner::UM_Audioreactive)) {
      DEBUG_PRINTLN(F("MSGEQ7: failed to allocate hw chip pins"));
      // Explicitly deallocate each pin; deallocatePin is a no-op for any
      // pin that was not successfully claimed by us, so this is always safe.
      PinManager::deallocatePin(_pinStrobe, PinOwner::UM_Audioreactive);
      PinManager::deallocatePin(_pinReset,  PinOwner::UM_Audioreactive);
      PinManager::deallocatePin(_pinOut,    PinOwner::UM_Audioreactive);
      return;
    }
    msgeq7_hw_gpio_init(_pinStrobe, _pinReset);
    // OUT is an analog input; no pinMode needed — analogRead() configures it.
    _hwChipReady = true;
  }

  void _deinitHardwareChip() {
    if (_hwChipReady) {
      PinManager::deallocatePin(_pinStrobe, PinOwner::UM_Audioreactive);
      PinManager::deallocatePin(_pinReset,  PinOwner::UM_Audioreactive);
      PinManager::deallocatePin(_pinOut,    PinOwner::UM_Audioreactive);
      _hwChipReady = false;
    }
  }

  void _readHardwareChip() {
    if (!_hwChipReady) return;
    msgeq7_hw_read(_pinStrobe, _pinReset, _pinOut,
                   _gainPercent, _squelchLevel, _lastHwReadMs);
  }

  // ── Member variables ───────────────────────────────────────────────────────

  // um_data output values (effects read these via pointers registered in setup)
  float    _volumeSmth    = 0.0f;
  uint16_t _volumeRaw     = 0;
  uint8_t  _fftResult[NUM_GEQ_CHANNELS] = {};
  uint8_t  _samplePeak    = 0;
  float    _FFT_MajorPeak = 1.0f;
  float    _my_magnitude  = 0.001f;

  // WLED data structures
  um_data_t    *_umData       = nullptr;
  AudioSource  *_audioSource  = nullptr;
  SWTaskParams *_swTaskParams = nullptr;

  // Settings (persisted to JSON config)
  bool     _enabled         = false;
  bool     _useHardwareChip = false;
  uint8_t  _dmType          = 1;         // 1 = Generic I2S (default)
  int8_t   _pinSD           = I2S_PIN_NO_CHANGE;
  int8_t   _pinWS           = I2S_PIN_NO_CHANGE;
  int8_t   _pinSCK          = I2S_PIN_NO_CHANGE;
  int8_t   _pinMCLK         = I2S_PIN_NO_CHANGE;
  int8_t   _pinStrobe       = -1;
  int8_t   _pinReset        = -1;
  int8_t   _pinOut          = -1;
  uint8_t  _gainPercent     = 128;       // 128 = unity gain
  uint8_t  _squelchLevel    = 10;        // noise gate on 0..255 output scale
  float    _filterQ         = MSGEQ7_DEFAULT_Q;
  uint16_t _attackMs        = 15;
  uint16_t _decayMs         = 80;

  // Runtime state
  bool     _initDone     = false;
  bool     _hwChipReady  = false;
  uint32_t _lastHwReadMs = 0;
  uint32_t _lastLoopMs   = 0;

  // PROGMEM key for config JSON
  static const char _name[];
};

const char MSGEQ7Usermod::_name[] PROGMEM = "MSGEQ7";

// ─── Registration ─────────────────────────────────────────────────────────────

static MSGEQ7Usermod msgeq7_usermod;
REGISTER_USERMOD(msgeq7_usermod);

// AI: end
