# Example PlatformIO Project Configuration Override
# ------------------------------------------------------------------------------
# Copy to platformio_override.ini to activate overrides
# ------------------------------------------------------------------------------
# Please visit documentation: https://docs.platformio.org/page/projectconf.html

[platformio]
#default_envs = WLED_tasmota_1M  # define as many as you need
default_envs = WLED_T-Display  # define as many as you need

#----------
# SAMPLE
#----------
[env:WLED_T-Display]
extends = env:esp32dev
upload_speed = 921600
monitor_speed = 115200
build_flags = ${common.build_flags} ${esp32.build_flags} -D WLED_RELEASE_NAME=\"WLED_T-Display\" 
  -D DATA_PINS=2 ; Data pin on TTGO T-Display board
  -D BTNPIN=35  ; Button on TTGO T-Display board
custom_usermods = ${env:esp32dev.custom_usermods} TTGO-T-Display
