#include "pov.h"

POV::POV() {}

bool POV::loadImage(const char * filename){
  if(!image.init(filename)) return false;
  if(!image.load()) return false;
  return true;
}

// Display a column directly from image memory
// For each pixel in the column (from row 0 to row height-1),
// compute its position in the BMP buffer and read the BGR values
void POV::showColumn(uint16_t colIndex) {
    // Ignore out-of-range columns: for widths == 2 (mod 4) the row-size check
    // below would still read one byte past the buffer when colIndex == width
    if (colIndex >= image.width()) return;
    uint16_t imgHeight = image.height();
    int rowSize = image.rowSize();
    
    // AI: below section was generated by an AI
    for (uint16_t i = 0; i < SEGLEN; i++) {
        if (i < imgHeight) {
            // Get pointer to this row in the image
            byte *rowStart = image.line(i);
            if (rowStart) {
                // Compute offset to the desired column (3 bytes per pixel: BGR)
                uint16_t pixelOffset = colIndex * 3;
                if (pixelOffset + 2 <= rowSize) {
                    // Read BGR values directly from image buffer
                    uint8_t b = rowStart[pixelOffset];
                    uint8_t g = rowStart[pixelOffset + 1];
                    uint8_t r = rowStart[pixelOffset + 2];
                    SEGMENT.setPixelColor(i, CRGB(r, g, b));
                    continue;
                }
	    }
	}
        // No valid pixel for this row/column: write black
        SEGMENT.setPixelColor(i, CRGB::Black);
    }
    // AI: end
}
