/*-------------------------------------------------------------------------

WLEDpixelBus - RMT output driver implementation

written by Damian Schneider @dedehai 2026

I would like to thank Michael C. Miller (@Makuna), NeoPixelBus helped me figure out the proper hardware initialisation.

RMT bus works on ESP32, S3, S2, C3 and C6 (tested) and should work on H2, C5 too (untested)
Supports auto-distribution of available RMT memory blocks to reduce interrupt frequency - needs to be refined if ever using RMT input
IDF V5: new rmt_tx driver + bytes encoder; reset/latch gap enforced via TX-done callback timestamp in show()
The glitch-free high priority interrupt implementation by @willmmiles is not yet available in V5 builds

-------------------------------------------------------------------------*/

#include "WLEDpixelBus.h"
#ifdef ARDUINO_ARCH_ESP32
#include "WLEDpixelBus_RMT.h"

#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5,0,0)
#include "esp_timer.h" // for esp_timer_get_time() (ISR-safe microsecond timestamp)
#endif

namespace WLEDpixelBus {

//==============================================================================
// Shared: auto-channel allocator state and constructor
//==============================================================================

// Static auto-channel counter for RmtBus
uint8_t RmtBus::expectedChannels = 1;
uint8_t RmtBus::allocatedCount = 0;
uint8_t RmtBus::currentChannelIndex = 0;
uint8_t RmtBus::usedBlocks = 0;
uint8_t RmtBus::activeChannelMask = 0;

RmtBus::RmtBus(int8_t pin, const LedTiming& timing, uint8_t colorOrder, uint8_t numChannels, uint8_t ledType)
  : _pin(pin)
  , _timing(timing)
  , _inverted(false)
  , _initialized(false)
#if ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(5,0,0)
  , _rmtChannel(RMT_CHANNEL_0)
#endif
{
  _encoder = ColorEncoder(colorOrder, numChannels, ledType);
  _ledType = ledType;
}

RmtBus::~RmtBus() {
  end();
}

void RmtBus::setColorOrder(uint8_t co) {
  _encoder = ColorEncoder(co, _encoder.getColorChannels(), _ledType);
}

// AI: below section was generated by an AI (works but needs a thorough review)

#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5,0,0)
//==============================================================================
// IDF V5 implementation (new RMT driver: rmt_tx + bytes encoder)
//==============================================================================

bool RmtBus::begin() {
  if (_initialized) return true;
  uint8_t blocksToUse = 1;
  uint8_t maxTxChannels = getRmtMaxChannels();

  // Auto-channel select with optimized memory block allocation (assumes no RMT RX usage)
  // note on channel allocation: channels are assigned such as to maximize the number of memory blocks
  // available to the channel to minimize the number of interrupts needed for buffer re-fills (less context switching overhead)
  // in V5 the request is passed as mem_block_symbols and the driver picks a channel with enough contiguous free blocks;
  // memory-block ownership (the V4 rmt_set_memory_owner hack on S3/C3) is handled internally by the driver
  // example: ESP32, 2 channels requested total -> use CH0 with 4 blocks and CH4 with 4 blocks
  // example: ESP32-S3 with 3 channels: use CH0 with 2 block, CH2 with 1 block, and CH3 with 5 blocks
  if (allocatedCount >= expectedChannels || allocatedCount >= maxTxChannels)
    return false;

  // total RMT memory blocks per group equals the total channel count (each channel owns one block,
  // TX and RX channels share the same memory pool)
  const uint8_t totalBlocks = SOC_RMT_CHANNELS_PER_GROUP;

  int left_channels = expectedChannels - allocatedCount - 1;

  if (left_channels == 0) {
    _channel = currentChannelIndex;
    blocksToUse = totalBlocks - usedBlocks;
  } else {
    int k = totalBlocks / expectedChannels;
    int max_k_for_index = maxTxChannels - currentChannelIndex - left_channels;
    if (k > max_k_for_index) k = max_k_for_index;
    if (k < 1) k = 1;

    _channel = currentChannelIndex;
    blocksToUse = k;
  }
  #ifdef RMT_USE_SINGLE_MEM_BLOCK
  blocksToUse = 1;
  #endif

  currentChannelIndex += blocksToUse;
  usedBlocks += blocksToUse;
  allocatedCount++;

  if (_channel >= (int8_t)maxTxChannels) {
    //DEBUG_PRINTF_P(PSTR("[WPB] RMT channel %d >= max %u, FAIL\n"), _channel, maxTxChannels);
    return false;
  }

  //DEBUG_PRINTF_P(PSTR("[WPB] RMT channel %d using %u blocks (total allocated: %u/%u)\n"), _channel, blocksToUse, allocatedCount, maxTxChannels);

  // RMT clock: 40MHz -> 25ns per tick
  const float tickNs = 25.0f;

  auto nsToTicks = [tickNs](uint16_t ns) -> uint16_t {
    uint16_t ticks = (uint16_t)((ns + tickNs / 2) / tickNs);
    return ticks > 0 ? ticks : 1;
  };

  rmt_symbol_word_t bit0 = {}, bit1 = {};
  bit0.level0 = 1; bit0.duration0 = nsToTicks(_timing.t0h_ns);
  bit0.level1 = 0; bit0.duration1 = nsToTicks(_timing.t0l_ns);
  bit1.level0 = 1; bit1.duration0 = nsToTicks(_timing.t1h_ns);
  bit1.level1 = 0; bit1.duration1 = nsToTicks(_timing.t1l_ns);

  rmt_tx_channel_config_t config = {};
  config.gpio_num = (gpio_num_t)_pin;
  config.clk_src = RMT_CLK_SRC_DEFAULT;
  config.resolution_hz = 40000000; // 40MHz, 25ns per tick
  config.mem_block_symbols = (size_t)blocksToUse * SOC_RMT_MEM_WORDS_PER_CHANNEL; // multi-block allocation: fewer refill interrupts
  config.trans_queue_depth = 2; // we always wait for tx done before transmitting, 1 would suffice
  config.intr_priority = 3;     // highest user priority in V5: refill ISR preempts other low/med ISRs, fewer underruns
  config.flags.invert_out = _inverted ? 1 : 0; // hardware signal inversion via GPIO matrix (replaces esp_rom_gpio hack)

  esp_err_t err = rmt_new_tx_channel(&config, &_rmtChannel);
  if (err != ESP_OK) {
    return false;
  }

  // bytes encoder: streams _encodeBuffer straight into RMT symbols, MSB first (replaces the V4 translator callbacks)
  rmt_bytes_encoder_config_t encCfg = {};
  encCfg.bit0 = bit0;
  encCfg.bit1 = bit1;
  encCfg.flags.msb_first = 1;
  err = rmt_new_bytes_encoder(&encCfg, &_bytesEncoder);
  if (err != ESP_OK) {
    rmt_del_channel(_rmtChannel); _rmtChannel = nullptr;
    return false;
  }

  // done callback stamps the end of each frame (used for the reset/latch gap enforcement in show())
  rmt_tx_event_callbacks_t cbs = {};
  cbs.on_trans_done = RmtBus::onTxDone;
  err = rmt_tx_register_event_callbacks(_rmtChannel, &cbs, this);
  if (err != ESP_OK) {
    rmt_del_encoder(_bytesEncoder); _bytesEncoder = nullptr;
    rmt_del_channel(_rmtChannel); _rmtChannel = nullptr;
    return false;
  }

  _txConfig = {};
  _txConfig.loop_count = 0;      // no looping
  _txConfig.flags.eot_level = 0; // keep line low after transmission (replaces idle_output_en / idle_level LOW)

  _resetUs = (_timing.reset_us > 0) ? _timing.reset_us : 300;
  // pretend the last transmission ended long ago so the first frame never waits (unsigned wrap-safe)
  _lastTxEndUs = (uint32_t)esp_timer_get_time() - _resetUs;

  err = rmt_enable(_rmtChannel);
  if (err != ESP_OK) {
    rmt_del_encoder(_bytesEncoder); _bytesEncoder = nullptr;
    rmt_del_channel(_rmtChannel); _rmtChannel = nullptr;
    return false;
  }

  _initialized = true;
  activeChannelMask |= (1 << _channel);
  if (!allocateEncodeBuffer(_numPixels, _encoder.getPixelBytes())) { end(); return false; }
  return true;
}

void RmtBus::end() {
  if (!_initialized) return;

  activeChannelMask &= ~(1 << _channel);

  rmt_tx_wait_all_done(_rmtChannel, 100);
  rmt_disable(_rmtChannel);
  if (_bytesEncoder) { rmt_del_encoder(_bytesEncoder); _bytesEncoder = nullptr; }
  if (_rmtChannel)   { rmt_del_channel(_rmtChannel); _rmtChannel = nullptr; }

  if (_pin >= 0) {
    gpio_reset_pin((gpio_num_t)_pin); // reset all pin settings
  }

  // Free encode buffer with the same allocator used in allocateEncodeBuffer() (plain malloc)
  if (_encodeBuffer) { free(_encodeBuffer); _encodeBuffer = nullptr; _encodeBufferSize = 0; }
  _initialized = false;
}

bool RmtBus::show() {
  // Encoding is done per-pixel in setPixelColor(); _encodeBuffer is ready to ship.
  if (!_initialized || !_encodeBuffer || _numPixels == 0 || !_rmtChannel) return false;

  esp_err_t err = rmt_tx_wait_all_done(_rmtChannel, 1000); // wait 1s max
  if (err != ESP_OK) return false;

  // enforce the reset/latch gap: onTxDone() stamped the end of the previous frame, wait out the remainder
  uint32_t elapsedUs = (uint32_t)esp_timer_get_time() - _lastTxEndUs; // unsigned subtraction is wrap-safe
  if (elapsedUs < _resetUs) delayMicroseconds(_resetUs - elapsedUs);

  err = rmt_transmit(_rmtChannel, _bytesEncoder, _encodeBuffer, _encodeBufferSize, &_txConfig);
  return (err == ESP_OK); // note: the V4 legacy path returned false on success (esp_err_t as bool), fixed here
}

bool RmtBus::canShow() const {
  if (!_initialized) return true;
  return (ESP_OK == rmt_tx_wait_all_done(_rmtChannel, 0)); // 0 timeout means "poll and return immediately"
}

void RmtBus::setInverted(bool inv) {
  _inverted = inv;
  // note: in V5 inversion is applied at channel creation (flags.invert_out);
  // if changed after begin() it takes effect on the next begin() only
}

// TX-done event callback (ISR context): stamp the end time of the frame.
// esp_timer_get_time() is safe to call from an ISR; keep this function short and IRAM resident.
bool IRAM_ATTR RmtBus::onTxDone(rmt_channel_handle_t channel, const rmt_tx_done_event_data_t *edata, void *user_ctx) {
  RmtBus *self = static_cast<RmtBus*>(user_ctx);
  self->_lastTxEndUs = (uint32_t)esp_timer_get_time();
  return false; // no higher priority task woken
}

// AI: end

#else
//==============================================================================
// IDF V4 implementation (legacy RMT driver + translator callbacks)
//==============================================================================

// Per-channel context table - stored in DRAM, 4 byte aligned for ISR access
DMA_ATTR RmtBus::RmtContext RmtBus::contexts[WPB_RMT_CHANNELS] = {};

// Explicit IRAM tranlator callback wrappers for each channel (ensures the function is placed in IRAM which is dropped when using templates)
void IRAM_ATTR RmtBus::translator_ch0(const void* s, rmt_item32_t* d, size_t ss, size_t w, size_t* ts, size_t* in) { translateInternal(0, s, d, ss, w, ts, in); }
void IRAM_ATTR RmtBus::translator_ch1(const void* s, rmt_item32_t* d, size_t ss, size_t w, size_t* ts, size_t* in) { translateInternal(1, s, d, ss, w, ts, in); }
#if SOC_RMT_TX_CANDIDATES_PER_GROUP > 2
void IRAM_ATTR RmtBus::translator_ch2(const void* s, rmt_item32_t* d, size_t ss, size_t w, size_t* ts, size_t* in) { translateInternal(2, s, d, ss, w, ts, in); }
void IRAM_ATTR RmtBus::translator_ch3(const void* s, rmt_item32_t* d, size_t ss, size_t w, size_t* ts, size_t* in) { translateInternal(3, s, d, ss, w, ts, in); }
#endif
#if SOC_RMT_TX_CANDIDATES_PER_GROUP > 4
void IRAM_ATTR RmtBus::translator_ch4(const void* s, rmt_item32_t* d, size_t ss, size_t w, size_t* ts, size_t* in) { translateInternal(4, s, d, ss, w, ts, in); }
void IRAM_ATTR RmtBus::translator_ch5(const void* s, rmt_item32_t* d, size_t ss, size_t w, size_t* ts, size_t* in) { translateInternal(5, s, d, ss, w, ts, in); }
void IRAM_ATTR RmtBus::translator_ch6(const void* s, rmt_item32_t* d, size_t ss, size_t w, size_t* ts, size_t* in) { translateInternal(6, s, d, ss, w, ts, in); }
void IRAM_ATTR RmtBus::translator_ch7(const void* s, rmt_item32_t* d, size_t ss, size_t w, size_t* ts, size_t* in) { translateInternal(7, s, d, ss, w, ts, in); }
#endif
// Jump table stored in DRAM, 4 byte aligned so ISR code can quickly find the correct wrapper
DMA_ATTR const sample_to_rmt_t RmtBus::callbacks[WPB_RMT_CHANNELS] = {
  RmtBus::translator_ch0, RmtBus::translator_ch1
#if SOC_RMT_TX_CANDIDATES_PER_GROUP > 2
  ,RmtBus::translator_ch2, RmtBus::translator_ch3
#endif
#if SOC_RMT_TX_CANDIDATES_PER_GROUP > 4
  ,RmtBus::translator_ch4, RmtBus::translator_ch5,
  RmtBus::translator_ch6, RmtBus::translator_ch7
#endif
};

void RmtBus::updateRmtTiming() {
  // RMT clock:  80MHz with div=2 -> 40MHz -> 25ns per tick
  const float tickNs = 25.0f;

  auto nsToTicks = [tickNs](uint16_t ns) -> uint16_t {
    uint16_t ticks = (uint16_t)((ns + tickNs / 2) / tickNs);
    return ticks > 0 ? ticks : 1;
  };

  rmt_item32_t bit0, bit1;
  bit0.level0 = 1; bit0.duration0 = nsToTicks(_timing.t0h_ns);
  bit0.level1 = 0; bit0.duration1 = nsToTicks(_timing.t0l_ns);
  bit1.level0 = 1; bit1.duration0 = nsToTicks(_timing.t1h_ns);
  bit1.level1 = 0; bit1.duration1 = nsToTicks(_timing.t1l_ns);

  contexts[(int)_rmtChannel].bit0 = bit0.val;
  contexts[(int)_rmtChannel].bit1 = bit1.val;
  contexts[(int)_rmtChannel].resetDuration = nsToTicks(_timing.reset_us * 1000);

}

bool RmtBus::begin() {
  if (_initialized) return true;
  uint8_t blocksToUse = 1;
  uint8_t maxTxChannels = getRmtMaxChannels();

  // Auto-channel select with optimized memory block allocation (assumes no RMT RX usage)
  // note on channel allocation: channels are assigned such as to maximize the number of memory blocks
  // available to the channel to minimize the number of interrupts needed for buffer re-fills (less context switching overhead)
  // C3 and S3 have less channels than blocks, so the last channel can always use additional blocks
  // example: ESP32, 2 channels requested total -> use CH0 with 4 blocks and CH4 with 4 blocks
  // example: ESP32-S3 with 3 channels: use CH0 with 2 block, CH2 with 1 block, and CH3 with 5 blocks
  if (allocatedCount >= expectedChannels || allocatedCount >= maxTxChannels)
    return false;

  uint8_t totalBlocks = 4; // default to 4 if unknown, should be safe
#if defined(CONFIG_IDF_TARGET_ESP32) || defined(CONFIG_IDF_TARGET_ESP32S3)
  totalBlocks = 8; // ESP32 and S3 have 8 blocks of RMT memory
#elif defined(CONFIG_IDF_TARGET_ESP32S2) || defined(CONFIG_IDF_TARGET_ESP32C3)  || defined(CONFIG_IDF_TARGET_ESP32C6)// note: C6 RMT hardware is the same as C3
  totalBlocks = 4; // other supported ESP32 variants have 4 blocks
#endif

  int left_channels = expectedChannels - allocatedCount - 1;

  if (left_channels == 0) {
    _channel = currentChannelIndex;
    blocksToUse = totalBlocks - usedBlocks;
  } else {
    int k = totalBlocks / expectedChannels;
    int max_k_for_index = maxTxChannels - currentChannelIndex - left_channels;
    if (k > max_k_for_index) k = max_k_for_index;
    if (k < 1) k = 1;

    _channel = currentChannelIndex;
    blocksToUse = k;
  }
  #ifdef RMT_USE_SINGLE_MEM_BLOCK
  blocksToUse = 1;
  #endif

  currentChannelIndex += blocksToUse;
  usedBlocks += blocksToUse;
  allocatedCount++;

  if (_channel >= (int8_t)maxTxChannels) {
    //DEBUG_PRINTF_P(PSTR("[WPB] RMT channel %d >= max %u, FAIL\n"), _channel, maxTxChannels);
    return false;
  }
  _rmtChannel = (rmt_channel_t)_channel;

  //DEBUG_PRINTF_P(PSTR("[WPB] RMT channel %d using %u blocks (total allocated: %u/%u)\n"), _channel, blocksToUse, allocatedCount, maxTxChannels);

  updateRmtTiming();

  rmt_config_t config = {};

  config.rmt_mode = RMT_MODE_TX;
  config.channel = _rmtChannel;
  config.gpio_num = (gpio_num_t)_pin;
  config.mem_block_num = blocksToUse;
  config.clk_div = 2;  // 40MHz

  config.tx_config.loop_en = false;
  config.tx_config.carrier_en = false;
  config.tx_config.idle_output_en = true;
  config.tx_config.idle_level = RMT_IDLE_LEVEL_LOW;

  esp_err_t err = rmt_config(&config);
  if (err != ESP_OK) {
    return false;
  }

  // Register hack for memory blocks normally assigned to RX (S2 / S3 / C3)   TODO: need this for ESP32 as well?
  // set owner to TX if blocks are shared with RX unit
#ifndef RMT_USE_SINGLE_MEM_BLOCK
  #if defined(CONFIG_IDF_TARGET_ESP32S3)
  for (int i = 4; i < 8; i++) {
    rmt_set_memory_owner((rmt_channel_t)i, RMT_MEM_OWNER_TX);
  }
  #elif defined(CONFIG_IDF_TARGET_ESP32C3)
  for (int i = 2; i < 4; i++) {
    rmt_set_memory_owner((rmt_channel_t)i, RMT_MEM_OWNER_TX);
  }
  #endif
#endif

#ifdef WPB_USE_RMTHI
  // Use the glitch-free high priority RMT driver (not available on C3 and IDF >= 5.0)
  err = RmtHiDriver::Install(_rmtChannel, contexts[(int)_rmtChannel].bit0, contexts[(int)_rmtChannel].bit1, contexts[(int)_rmtChannel].resetDuration, blocksToUse);
  if (err != ESP_OK) {
    //DEBUG_PRINTF_P(PSTR("[WPB] rmtHi Install failed: %d\n"), err);
    return false;
  }
#else
  // Use the IDF rmt driver + translator
  err = rmt_driver_install(_rmtChannel, 0, (ESP_INTR_FLAG_IRAM | ESP_INTR_FLAG_LOWMED));
  if (err != ESP_OK) {
    return false;
  }

  err = rmt_translator_init(_rmtChannel, callbacks[(int)_rmtChannel]);
  if (err != ESP_OK) {
    rmt_driver_uninstall(_rmtChannel);
    return false;
  }
#endif

  // route the pin, use hardware signal inversion via GPIO matrix if _inverted
  esp_rom_gpio_connect_out_signal(_pin, RMT_SIG_OUT0_IDX + (int)_rmtChannel, _inverted, false);

  if (_initialized) esp_rom_gpio_connect_out_signal(_pin, RMT_SIG_OUT0_IDX + (int)_rmtChannel, _inverted, false);

  _initialized = true;
  activeChannelMask |= (1 << _channel);
  if (!allocateEncodeBuffer(_numPixels, _encoder.getPixelBytes())) { end(); return false; }
  return true;
}

void RmtBus::end() {
  if (!_initialized) return;

  activeChannelMask &= ~(1 << _channel);
#ifdef WPB_USE_RMTHI
  RmtHiDriver::Uninstall(_rmtChannel);
#else
  rmt_driver_uninstall(_rmtChannel);
#endif
  if (_pin >= 0) {
    gpio_reset_pin((gpio_num_t)_pin); // reset all pin settings
  }

  // Free encode buffer with the same allocator used in allocateEncodeBuffer() (plain malloc)
  if (_encodeBuffer) { free(_encodeBuffer); _encodeBuffer = nullptr; _encodeBufferSize = 0; }
  _initialized = false;
}

bool RmtBus::show() {
  // Encoding is done per-pixel in setPixelColor(); _encodeBuffer is ready to ship.
  if (!_initialized || !_encodeBuffer || _numPixels == 0) return false;

  const size_t dataLen = _encodeBufferSize;
  esp_err_t err;
#ifdef WPB_USE_RMTHI
  err = (RmtHiDriver::Write(_rmtChannel, _encodeBuffer, dataLen) == ESP_OK);
#else
  err = rmt_wait_tx_done(_rmtChannel, 1000 / portTICK_PERIOD_MS); // wait 1s max
  if (err == ESP_OK)
    err = rmt_write_sample(_rmtChannel, _encodeBuffer, dataLen, false); // CRITICAL BUG: crashes on C3 under heavy UI refresh, this line is reached, then it stalls for some unknown reason
#endif
  return err;
}

bool RmtBus::canShow() const {
  if (!_initialized) return true;
#ifdef WPB_USE_RMTHI
  return (ESP_OK == RmtHiDriver::WaitForTxDone(_rmtChannel, 0)); // 0 timout means "poll and return immediately"
#else
  return (ESP_OK == rmt_wait_tx_done(_rmtChannel, 0));
#endif
}

void RmtBus::setInverted(bool inv) {
  _inverted = inv;
}

//note: using O2 optimization has little to no effect on FPS
void IRAM_ATTR RmtBus::translateInternal(uint8_t channel, const void* src, rmt_item32_t* dest, size_t src_size, size_t wanted_num, size_t* translated_size, size_t* item_num) {

  // safety check - should never happen
  if (src == nullptr || dest == nullptr) {
    *translated_size = 0;
    *item_num = 0;
    return;
  }

  const uint8_t* psrc = (const uint8_t*)src;

  // Cache instance timings in registers for maximum ISR speed
  const uint32_t bit0 = contexts[channel].bit0;
  const uint32_t bit1 = contexts[channel].bit1;

  // Calculate how many full bytes we can translate based on RMT buffer space (wanted_num)
  const uint32_t items_limit = wanted_num / 8;
  const uint32_t bytes_to_process = (src_size > items_limit) ? items_limit : src_size;
  *translated_size = bytes_to_process;
  *item_num = bytes_to_process * 8;

  for (uint32_t i = 0; i < bytes_to_process; i++) {
    const uint8_t data = psrc[i];
    rmt_item32_t* pdest = &dest[i * 8];

    // using loop unrolling makes this faster avoiding bit shifts, loop overhead and lets the compiler optimize more
    pdest[0].val = (data & 0x80) ? bit1 : bit0;
    pdest[1].val = (data & 0x40) ? bit1 : bit0;
    pdest[2].val = (data & 0x20) ? bit1 : bit0;
    pdest[3].val = (data & 0x10) ? bit1 : bit0;
    pdest[4].val = (data & 0x08) ? bit1 : bit0;
    pdest[5].val = (data & 0x04) ? bit1 : bit0;
    pdest[6].val = (data & 0x02) ? bit1 : bit0;
    pdest[7].val = (data & 0x01) ? bit1 : bit0;
  }

  // If max_bytes == src_size, it means we've reached the end of the LED strip.
  if (bytes_to_process > 0 && bytes_to_process == src_size) {
    dest[(bytes_to_process * 8) - 1].duration1 = contexts[channel].resetDuration; // set the last (low) pulse to reset duration
  }

//  *translated_size = bytes_to_process;
//  *item_num = bytes_to_process * 8;
}

#endif // ESP_IDF_VERSION

} // namespace WLEDpixelBus
#endif // ARDUINO_ARCH_ESP32