Import("env")
import json
import os
from os.path import realpath

import SCons.Errors
from SCons.Script import Action

global_env = DefaultEnvironment()

shims_dir = realpath("shims")
# BUILD_DIR is itself defined as "$PROJECT_BUILD_DIR/$PIOENV" (see PlatformIO's
# builder/main.py) — env["BUILD_DIR"] returns that raw, unexpanded template
# string, not a real path. Without subst(), os.path.join() below would create
# a literal "./shims/$PROJECT_BUILD_DIR/$PIOENV/TFT_eSPI_compat" directory.
build_shims_dir = os.path.join(global_env.subst("$BUILD_DIR"), "TFT_eSPI_compat")

# Create the generated-file directory now so get_include_dirs() reports it
# and so SCons's FindFile can locate Command nodes inside it.
os.makedirs(build_shims_dir, exist_ok=True)

# Inject shims/ and build_shims_dir into DefaultEnvironment(), so they'll be
# visible anywhere in the build.  They're appended, not prepended, so any
# real SPIFFS.h or tft_setup.h will take precedence over these.
global_env.AppendUnique(CPPPATH=[shims_dir, build_shims_dir])

# Also add to our own lib env so load_usermods.py propagates them to usermods
# via cached_add_includes → dep.get_include_dirs().
env.AppendUnique(CPPPATH=[shims_dir, build_shims_dir])

# ---------------------------------------------------------------------------
# Generate tft_setup.h — proper SCons target
# ---------------------------------------------------------------------------
# TFT_eSPI.h checks __has_include(<tft_setup.h>); providing the file lets us
# inject the display config via TFT_eSPI's own hook without patching it.
#
# The file is generated from the resolved display-setup configuration so
# SCons knows to rebuild it (and therefore recompile TFT_eSPI) exactly when
# that configuration changes — not on every build.
#
# SCons's CScanner does not parse __has_include(), so shims/User_Setup.h
# carries a plain #include <tft_setup.h> that gives the scanner a normal
# include directive to follow, ensuring the generated file is built before
# any TFT_eSPI source is compiled.

_lib_env = env  # capture before the function definition shadows the name

# Enumerating every file that could influence custom_display_setup /
# TFT_DISPLAY_SETUP_DEFAULT is unbounded, so we depend on the *resolved
# value* instead, via a real intermediate file (SCons Value() nodes don't
# track post-construction writes for signature purposes, so they can't be
# used as a build-time-computed dependency). Resolution needs
# GetLibBuilders(), which isn't populated until build time, so it happens
# in a build action rather than here at parse time. AlwaysBuild reruns the
# resolution every build, but we only rewrite the file when the resolved
# value actually changes.
def _resolve_display_setup(target, source, env):   # argument names are required by SCons
    genv = DefaultEnvironment()
    all_lbs = _lib_env.GetLibBuilders()

    display_setup = (
        genv.GetProjectOption("custom_display_setup", "")
        or genv.get("TFT_DISPLAY_SETUP_DEFAULT", "")
    )

    setup_path = None
    if display_setup:
        if os.path.isfile(display_setup):
            setup_path = display_setup
        else:
            search_paths = [
                genv["PROJECT_SRC_DIR"],
                genv["PROJECT_INCLUDE_DIR"],
                *[d for lb in all_lbs for d in lb.get_include_dirs()],
            ]
            setup_path = next(
                (
                    os.path.join(str(p), display_setup)
                    for p in search_paths
                    if os.path.isfile(os.path.join(str(p), display_setup))
                ),
                None,
            )

    target_path = str(target[0])
    new_contents = json.dumps([display_setup, setup_path])
    if os.path.isfile(target_path):
        with open(target_path) as f:
            if f.read() == new_contents:
                return
    with open(target_path, "w") as f:
        f.write(new_contents)


_resolved_display_setup = global_env.Command(
    os.path.join(build_shims_dir, "display_setup.resolved.json"),
    [],
    Action(_resolve_display_setup, cmdstr=None),
)
global_env.AlwaysBuild(_resolved_display_setup)
# NoCache: this target has no real sources, so its CacheDir signature never
# changes — without this, CacheDir would keep serving the first build's
# file instead of re-running _resolve_display_setup.
global_env.NoCache(_resolved_display_setup)
# Precious: SCons deletes a target before rebuilding it by default, which
# would defeat the write-if-changed check above (it needs to read the
# previous build's file to compare against).
global_env.Precious(_resolved_display_setup)


def _generate_tft_setup(target, source, env):   # argument names are required by SCons
    with open(str(source[0])) as f:
        display_setup, setup_path = json.load(f)

    lines = ["// Generated by TFT_eSPI_compat — do not edit\n", "#pragma once\n"]

    if display_setup:
        if setup_path:
            escaped = setup_path.replace("\\", "\\\\")
            lines.append(f'#include "{escaped}"\n')
        else:
            raise SCons.Errors.StopError(
                f"TFT_eSPI_compat: display setup '{display_setup}' not found "
                "in any include path"
            )

    os.makedirs(os.path.dirname(str(target[0])), exist_ok=True)
    with open(str(target[0]), "w") as f:
        f.writelines(lines)


global_env.Command(
    os.path.join(build_shims_dir, "tft_setup.h"),
    _resolved_display_setup,
    Action(_generate_tft_setup, cmdstr="Generating tft_setup.h"),
)
