    name: Notify Discord on PR Merge
    on:
      workflow_dispatch:
      pull_request_target:
        types: [closed]

    jobs:
      notify:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        steps:
        - name: Get User Permission
          id: checkAccess
          uses: actions-cool/check-user-permission@v2
          with:
            require: write
            username: ${{ github.triggering_actor }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Check User Permission
          if: steps.checkAccess.outputs.require-result == 'false'
          run: |
            echo "${{ github.triggering_actor }} does not have permissions on this repo."
            echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
            echo "Job originally triggered by ${{ github.actor }}"
            exit 1
        - name: Send Discord notification
          run: |
            curl -H "Content-Type: application/json" -d '{"content": "Pull Request ${{ github.event.pull_request.number }} merged by ${{ github.actor }}"}' ${{ secrets.DISCORD_WEBHOOK_BETA_TESTERS }}
